In [3]:
# 만약 .requires_grad 속성을 True 로 설정하면, 
# 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작합니다.
import torch

# 연산을 기록
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
# y는 연산의 결과로 생성된 것이므로 grad_fn을 갖는다.
print(y.grad_fn)

In [7]:
z = y * y *3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()

In [12]:
# 변화도 d(out)/dx를 출력
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
# 벡터 야코비안 곱의 예제를 살펴보도록 하겠습니다.
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
  y = y*2

print(y)

tensor([-626.4447,  762.5673, -864.4827], grad_fn=<MulBackward0>)


In [14]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [15]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False


In [16]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
