In [1]:
from __future__ import print_function
import torch

In [3]:
# 초기화 되지 않은 행렬 생성
x = torch.empty(5,3)
print(x)

tensor([[3.1183e+04, 3.0723e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
# 무작위로 초기화 한 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.4724, 0.5002, 0.6124],
        [0.9123, 0.1399, 0.2741],
        [0.8382, 0.3783, 0.4081],
        [0.2004, 0.4568, 0.0067],
        [0.4418, 0.4949, 0.8673]])


In [5]:
#dtype이 long이고, 0으로 채워진 행렬 생성 
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# 데이터로부터 tensor직접 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# 기존 tensor를 바탕으로 새로운 tensor 생성
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1903, -0.6140, -0.9095],
        [-0.5380,  0.0624,  0.6313],
        [ 1.3695, -0.2420,  0.3390],
        [ 0.2807, -1.6594, -0.9933],
        [-0.2345, -0.3836,  0.8818]])


In [8]:
# 행렬의 크기 구하기
print(x.size())

torch.Size([5, 3])


In [10]:
# 행렬 덧셈 1
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.4837, -0.5828, -0.4794],
        [-0.2200,  0.7112,  0.7671],
        [ 1.6305,  0.7378,  0.9248],
        [ 0.8869, -0.7383, -0.2350],
        [ 0.4827, -0.1961,  1.8585]])


In [11]:
# 행렬 덧셈 2
print(torch.add(x,y))

tensor([[ 0.4837, -0.5828, -0.4794],
        [-0.2200,  0.7112,  0.7671],
        [ 1.6305,  0.7378,  0.9248],
        [ 0.8869, -0.7383, -0.2350],
        [ 0.4827, -0.1961,  1.8585]])


In [12]:
# 행렬 덧셈 3
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4837, -0.5828, -0.4794],
        [-0.2200,  0.7112,  0.7671],
        [ 1.6305,  0.7378,  0.9248],
        [ 0.8869, -0.7383, -0.2350],
        [ 0.4827, -0.1961,  1.8585]])


In [13]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 0.4837, -0.5828, -0.4794],
        [-0.2200,  0.7112,  0.7671],
        [ 1.6305,  0.7378,  0.9248],
        [ 0.8869, -0.7383, -0.2350],
        [ 0.4827, -0.1961,  1.8585]])


In [14]:
print(x[:,1])

tensor([-0.6140,  0.0624, -0.2420, -1.6594, -0.3836])


In [15]:
# 텐서의 크기, 모양 변경할 때 torch.view 사용
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1은 다른 차원에서 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
# tensor에 하나의 값만 존재한다면 .item()으로 숫자값얻기 가능
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4506])
1.450631856918335


In [18]:
# tensor(torch) -> array(numpy)
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
# tensor(torch) <- array(numpy)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
