In [1]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)

2
int32
4
15


numpy.ndarray

In [14]:
a = np.array([2,3,4])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

[2 3 4]
int32
float64


In [15]:
a = np.array([1,2,3,4])

In [17]:
b = np.array([(1.3,2,3),(4,5,6)])
print(b)

[[1.3 2.  3. ]
 [4.  5.  6. ]]


In [18]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((5,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56593017e-307, 8.34441742e-308],
       [8.90104239e-307, 1.33511290e-306, 1.69118108e-306,
        2.22520967e-306, 8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.15710088e-306, 6.23056330e-307],
       [1.60219578e-306, 7.56601165e-307, 6.23061763e-307,
        9.34607074e-307, 8.90098127e-307],
       [8.90108313e-307, 6.23053954e-307, 2.22523004e-306,
        2.22522596e-306, 2.22809558e-312]])

In [24]:
np.arange(10,30,5)  # 시작, 끝, 간격

array([10, 15, 20, 25])

In [25]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
from numpy import pi
np.linspace(0,2,9) # 공간을 linear하게 나눔

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
x = np.linspace(0,2*pi,100)
f = np.sin(x)
print(f)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [32]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [35]:
np.set_printoptions(threshold=100)
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [38]:
a = np.array([20,30,40,50])
b = np.arange(4)
b
c = a-b
c  # element-wise
print(a)
print(b)
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [40]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [41]:
print(np.sin(a))
print(10 * np.sin(a))
a<35

[ 0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False])

In [42]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

A*B

array([[2, 0],
       [0, 4]])

In [45]:
#행렬의 곱
print(A@B)
print(A.dot(B))

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [53]:
rg = np.random.default_rng(1)  # random seed 같은값이 나옴
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))  # float로 저장되어 있음
print("b",b)
a*= 3
print("a",a)
a = np.ones((2,3), dtype=int)

# 정수로 변환
b_ = np.int32(b)
a += b_
print("a",a)
print("b",b)
print("b_",b_)

a = a*3
print("a",a)

# 실수로 변환
a_ = np.float64(a)
a_ += b
print("a_", a)

b [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
a [[3 3 3]
 [3 3 3]]
a [[1 1 1]
 [1 1 1]]
b [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
b_ [[0 0 0]
 [0 0 0]]
a [[3 3 3]
 [3 3 3]]
a_ [[3 3 3]
 [3 3 3]]


In [54]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b.dtype.name)
c = a+b # 더정확한 데이터를 통해 더해짐
c

float64


array([1.        , 2.57079633, 4.14159265])

In [58]:
d = np.exp(c*1j) # j 는 허수 : 신호처리에서 사용됨
print(d)
d.dtype.name

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [59]:
a = rg.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


In [61]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))
print(b.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [62]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2.,-1.,4.])
print(C.dtype)
np.add(B,C)

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
float64


array([2., 0., 6.])

In [68]:
a = np.arange(10) ** 3
print(a)
print(a[2])
print(a[2:5])
a[:6:2]  # 처음부터 6까지 간격을 2로
print(a)
print(a[::-1]) # 거꾸로 하나씩 돌아오겠다

for i in a:
    print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[  0   1   8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [73]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
print(b)
print(b[2,3])
print(b[0:5,1])
print(b[:,1])
print(b[1:3,:])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
