In [10]:
import numpy as np

rg = np.random.default_rng(1)
a = np.floor(10*rg.random((3,4)))
print(a)
print(a.shape)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
(3, 4)


In [11]:
b = a.ravel()  # 1차원으로 바꾸어줌
print(b.shape)

c = a.reshape(6,2)
print(c.shape)

d = c.T  # transpose
print(d.shape)

print(a)
a.resize((2,6))
print(a)

# a.reshape : a에 아무런 변화가 없음
# a.resize : a를 직접 바꿈


(12,)
(6, 2)
(2, 6)
[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
[[5. 9. 1. 9. 3. 4.]
 [8. 4. 5. 0. 7. 5.]]


In [12]:
b = a.reshape(3,-1)  # -1 : 딱맞게 떨어지게 만들어줌
print(b)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]


In [22]:
a = np.floor(10*rg.random((2,2)))  # floor : 내림
print(a)
print(np.floor(2.8))
print(np.round(2.3))
print(np.ceil(2.3))

b = np.floor(10*rg.random((2,2)))
print(b)

x = np.vstack((a,b))  # vertical: 세로로 쌓다 
y = np.hstack((a,b))  # horisontal: 가로로 쌓다
print(x)
print(y)
np.column_stack((a, b))  # 가로방향으로 stack


[[8. 8.]
 [8. 4.]]
2.0
2.0
3.0
[[2. 0.]
 [6. 7.]]
[[8. 8.]
 [8. 4.]
 [2. 0.]
 [6. 7.]]
[[8. 8. 2. 0.]
 [8. 4. 6. 7.]]


array([[8., 8., 2., 0.],
       [8., 4., 6., 7.]])

In [25]:
from numpy import newaxis
a = np.array([4.,2.])

print(a[:,newaxis])
print(a)

[[4.]
 [2.]]
[4. 2.]


In [26]:


a = np.array([4.,2.])
b = np.array([3.,8.])

# 1차원을 2차원으로 바꿔줌
print(np.column_stack((a,b)))  # 각각의 어레이를 유지한채 스택
print(np.hstack((a,b)))  # 각각의 데이터 하나하나를 스택

print(np.column_stack((a[:,newaxis],b[:,newaxis])))
print(np.column_stack((a[:,newaxis],b[:,newaxis])))

[[4. 3.]
 [2. 8.]]
[4. 2. 3. 8.]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


In [27]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [29]:
a = np.floor(10*rg.random((2,12)))
print(a)

[[8. 2. 2. 6. 8. 9. 1. 4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6. 2. 7. 2. 8. 0. 8. 1.]]


In [31]:
# split
b = np.hsplit(a,3) # 세로방향
print(b) 
b = np.hsplit(a,(3,4))
print(b)

[array([[8., 2., 2., 6.],
       [6., 9., 8., 8.]]), array([[8., 9., 1., 4.],
       [6., 2., 7., 2.]]), array([[8., 4., 5., 0.],
       [8., 0., 8., 1.]])]
[array([[8., 2., 2.],
       [6., 9., 8.]]), array([[6.],
       [8.]]), array([[8., 9., 1., 4., 8., 4., 5., 0.],
       [6., 2., 7., 2., 8., 0., 8., 1.]])]


In [34]:
# copy

a = np.arange(12).reshape((3,4))
print(a)
b=a
b is a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


True

In [35]:
def f(x):
    print(id(x))

print(id(a))
f(a)

1958957822880
1958957822880


In [41]:
# shallow copy

## a 와 똑같은 데이터를 가진 어레이를 생성하지만 같지는 않다.
fuck = a.view()
## 그대신 fuck의 shape을 바꾸면 a의 shape은 바뀌지 않지만, fuck의 데이터를 바꾸면 a의 데이터도 바뀜

print(fuck is a)
print(fuck.base is a)
print(fuck.flags.owndata)

False
False
False


In [42]:
# deep copy
d = a.copy()
d is a

False

In [43]:
d.base is a

False

In [44]:
d[0,0]

0

In [46]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [48]:
a = np.arange(12)**2
i = np.array([1,1,3,5,8])
print(a)
print(a[i])

# dimention을 바꿀수 있다.
j = np.array([[3,4],[9,7]])
print(a[j])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 25 64]
[[ 9 16]
 [81 49]]


In [49]:
palette = np.array([
    [0,0,0],       # black 
    [255,0,0],     # red
    [0,255,0],     # green 
    [0,0,255],     # blue
    [255,255,255]  # white
])

image = np.array([[0,1,2,0],[0,3,4,0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
i = 